<Project>
  <Import Project="GrowthRibbon.Validation.targets" />
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Assembly-CSharp'">
    <Compile Remove="Assets\Scripts\Interaction\WaterwayGateController.cs" />
    <Compile Include="Assets\Scripts\Interaction\WaterwayGateController.cs" />
    <Compile Remove="Assets\Scripts\Interaction\WaterwayGateTargetFade.cs" />
    <Compile Include="Assets\Scripts\Interaction\WaterwayGateTargetFade.cs" />
  </ItemGroup>
</Project>
